location1 = Location.create! name: "Coffee", short: 'coffee'
location2 = Location.create! name: "Speakers Room", short: 'speaker'
location3 = Location.create! name: "Drinks", short: 'drink'
location4 = Location.create! name: "Play some table soccer", short: 'soccer'
location5 = Location.create! name: "Hacktrack", short: 'hack'
location6 = Location.create! name: "Foodstation (Meat)", short: 'meat'
location7 = Location.create! name: "FoodStation (Veggie)", short: 'veggie'
